# Generated by Django 2.0.7 on 2018-08-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=20)),
                ('lon', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('icon', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navi.Subject'),
        ),
    ]
