# Generated by Django 2.0.7 on 2018-08-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='extra',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='subject',
            name='extra',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
