# Generated by Django 2.0.7 on 2018-08-28 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0002_auto_20180827_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
